Implementing Jekyll for BeSLab
Be-Secure/BeSLab pull request #61
Opened 2024-05-08 17:28 UTC by sudhirverma

2024-05-15 07:23 UTC, sudhirverma commented
To test this PR

```
1. cd docs
2. bundle install
3. bundle exec jekyll serve
```

2024-05-15 10:25 UTC, anilsingla requested changes
Please check the review comments.

2024-05-15 10:25 UTC, anilsingla commented on docs/_docs/01-quick-start-guide.md
> +excerpt: "How to quickly install and setup Minimal Mistakes for use with GitHub Pages."
Need to update excerpt.

2024-05-15 10:25 UTC, anilsingla commented on docs/_docs/01-quick-start-guide.md
> +**Note:** BeSLab only suported on Ubuntu based system.
At present its supporting only Ubuntu. May be we can say it at present only Ubuntu with version 22.04 specifically.

2024-05-15 10:25 UTC, anilsingla commented on docs/_docs/05-configuration.md
> +The `genesis.yaml` file contains various configuration options that define the setup of the BeSLab instance. These options include specifying the lab type, lab name, version of BeSMan (Be-Secure Mana
Add Code Collaboration Tool as well. Code Collaboration tool is the main component of BeSLab.

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/about.md
> +excerpt: "Minimal Mistakes is a flexible two-column Jekyll theme."
update excerpt

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/lorem-ipsum.md
> +title: "Lorem Ipsum"
Do we need this page?

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/page-a.md
> +---
Do we need this page ? If so do we need to change content ?

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/page-b.md
> +---
we can delete this page if not needed.

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/pets.md
> +---
I think extra page please check.

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/portfolio-archive.md
> +---
Do we need portfolio?

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/sample-page.md
> +---
I think this page not needed.

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/recipes-archive.md
> +---
What is this page for ?

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/splash-page.md
> +---
I think we need to update this page to display Be-Secure branding. Check once.

2024-05-15 10:25 UTC, anilsingla commented on docs/_pages/terms.md
> +---
We need to define our terms and policy I think. Can we check with Hari or Vinod for it?

2024-05-15 10:25 UTC, anilsingla commented on docs/_posts/2024-05-14-post-exclude-search.md
> +  - Jekyll
I think we need to change the category to something else.

2024-05-16 10:25 UTC, anilsingla commented
Looks good to me

2024-05-16 10:25 UTC, anilsingla commented
Looks Good!!

2024-05-16 10:27 UTC, anilsingla approved these changes

2024-05-16 10:27 UTC, merged